version: 1.0.18.{build}

os: Visual Studio 2019

environment:
  matrix:
    - platform: Win32
      configuration: Debug
    - platform: Win32
      configuration: Release
    - platform: x64
      configuration: Debug
    - platform: x64
      configuration: Release

matrix:
  fast_finish: false

init: msbuild /version

build:
  parallel: true
  project: libsodium.vcxproj
  verbosity: minimal
