#ifndef LADDER_BASE_NAMESPACE_H
#define LADDER_BASE_NAMESPACE_H

#define  ladder_base  crypto_scalarmult_curve25519_sandy2x_ladder_base
#define _ladder_base _crypto_scalarmult_curve25519_sandy2x_ladder_base

#endif //ifndef LADDER_BASE_NAMESPACE_H

