/*
 * src/ref/serpent_ctr.c
 *
 * Serpent-256 CTR mode streaming cipher — scalar C reference implementation.
 *
 * Counter format: 128-bit little-endian.
 *   ctr[0] is the least-significant byte; increment propagates carry from
 *   ctr[0] upward.  The nonce IS the initial counter value (all 16 bytes),
 *   matching leviathan-crypto/src/asm/serpent/ctr.ts resetCounter() semantics.
 *
 * CTR is symmetric: decryption is identical to encryption.  Call either
 * function for both directions.
 *
 * Three entry points:
 *
 *   serpent_ctr_xor         — nonce sets counter to exact value, no offset
 *   serpent_ctr_xor_ic      — adds a 64-bit block-count offset (low 64 bits)
 *   serpent_ctr_xor_ic128   — adds a full 128-bit block-count offset
 *
 * The ic variants are used by worker pools to divide a large plaintext into
 * independent chunks, each worker calling xor_ic128 with its own start block.
 * xor_ic is the libsodium-compatible variant matching crypto_stream_*_xor_ic.
 *
 * All three functions are safe for in-place operation (out == in).
 *
 * Verified against leviathan-crypto CTR vectors A–E (ctr_vectors.ts),
 * which were generated by ctr_harness.c (floppy1 reference implementation).
 */

#include "serpent_ctr.h"
#include "serpent.h"
#include "utils.h"   /* sodium_memzero */

#include <string.h>
#include <stdint.h>

/* ── 128-bit LE counter helpers ──────────────────────────────────────────── */

/*
 * ctr_inc — increment a 128-bit LE counter in-place.
 *
 * Byte 0 is the LSB.  Carry propagates upward from byte 0.
 * Wraps around from 0xFF×16 to 0x00×16.
 *
 * This is the core counter step used by every block, matching
 * leviathan-crypto incrementCounter():
 *   const b = load<u8>(COUNTER_OFFSET + i) + 1
 *   store<u8>(..., b & 0xFF)
 *   if (b < 256) break
 */
static inline void ctr_inc(uint8_t ctr[16])
{
	int i;
	for (i = 0; i < 16; i++)
		if (++ctr[i] != 0) break;
}

/*
 * ctr_add64 — add a 64-bit block count to a 128-bit LE counter in-place.
 *
 * Treats ctr[0..15] as a 128-bit LE integer and adds n, with carry from
 * the low 64 bits into the high 64 bits.  Used to implement xor_ic.
 *
 * Note: we add to the COUNTER (nonce-initialised), not to a separate ic
 * field — the entire counter is the nonce + offset.
 */
static inline void ctr_add64(uint8_t ctr[16], uint64_t n)
{
	int      i;
	uint32_t carry = 0;

	for (i = 0; i < 8; i++) {
		uint32_t s = (uint32_t)ctr[i] + (uint32_t)(n & 0xff) + carry;
		ctr[i] = (uint8_t)s;
		carry = s >> 8;
		n >>= 8;
	}
	/* Propagate carry into high 64 bits. */
	for (i = 8; i < 16 && carry; i++) {
		uint32_t s = (uint32_t)ctr[i] + carry;
		ctr[i] = (uint8_t)s;
		carry = s >> 8;
	}
}

/*
 * ctr_add128 — add a 128-bit value (lo + hi) to the counter in-place.
 *
 * lo occupies bytes 0–7 (LE), hi occupies bytes 8–15 (LE).
 * Used by serpent_ctr_xor_ic128 for full-precision absolute positioning.
 */
static inline void ctr_add128(uint8_t ctr[16], uint64_t lo, uint64_t hi)
{
	int      i;
	uint32_t carry = 0;

	for (i = 0; i < 8; i++) {
		uint32_t s = (uint32_t)ctr[i] + (uint32_t)(lo & 0xff) + carry;
		ctr[i] = (uint8_t)s;
		carry = s >> 8;
		lo >>= 8;
	}
	for (i = 8; i < 16; i++) {
		uint32_t s = (uint32_t)ctr[i] + (uint32_t)(hi & 0xff) + carry;
		ctr[i] = (uint8_t)s;
		carry = s >> 8;
		hi >>= 8;
	}
	/* Final carry out of bit 127 is discarded (counter wraps). */
}

/* ── Core CTR stream function ────────────────────────────────────────────── */

/*
 * serpent_ctr_xor_core — inner loop shared by all three public entry points.
 *
 * ctr is passed in already initialised (nonce ± offset).  Mutated in-place
 * by ctr_inc after each block.  Wiped on return.
 */
static void
serpent_ctr_xor_core(const uint32_t *sk,
                     uint8_t         ctr[16],
                     const uint8_t  *in,
                     uint8_t        *out,
                     size_t          len)
{
	uint8_t ks[16];   /* keystream block */
	size_t  i, blen;

	while (len > 0) {
		/* Encrypt the current counter block to produce 16 keystream bytes. */
		serpent_encrypt(sk, ctr, ks);

		blen = len < 16 ? len : 16;
		for (i = 0; i < blen; i++)
			out[i] = in[i] ^ ks[i];

		in  += blen;
		out += blen;
		len -= blen;

		ctr_inc(ctr);
	}

	sodium_memzero(ks, sizeof ks);
}

/* ── Public API ──────────────────────────────────────────────────────────── */

/*
 * serpent_ctr_xor — encrypt/decrypt a message with counter starting at nonce.
 *
 *   sk     : 132-word subkey array from serpent_keyschedule()
 *   nonce  : 16-byte initial counter value (little-endian 128-bit integer)
 *   in     : input bytes (plaintext or ciphertext)
 *   out    : output bytes — may alias in (in-place is safe)
 *   len    : number of bytes to process
 *
 * The nonce is NOT consumed.  The caller retains it for subsequent calls.
 * To process a 1-TB stream in one shot, call with a single in/out pointer.
 * To process independently in parallel chunks, use xor_ic128 instead.
 */
void serpent_ctr_xor(const uint32_t *sk,
                     const uint8_t   nonce[16],
                     const uint8_t  *in,
                     uint8_t        *out,
                     size_t          len)
{
	uint8_t ctr[16];
	memcpy(ctr, nonce, 16);
	serpent_ctr_xor_core(sk, ctr, in, out, len);
	sodium_memzero(ctr, sizeof ctr);
}

/*
 * serpent_ctr_xor_ic — encrypt/decrypt with a 64-bit initial counter offset.
 *
 *   ic     : block count to add to nonce before starting (low 64 bits).
 *            Allows seeking to byte position (ic * 16) within the stream.
 *
 * Matches the libsodium xor_ic convention.  The full counter is:
 *   ctr = nonce + ic  (128-bit LE addition, carry from low to high 64 bits)
 *
 * Example: to process bytes [512, 1024) of a stream, call with ic = 32.
 */
void serpent_ctr_xor_ic(const uint32_t *sk,
                        const uint8_t   nonce[16],
                        uint64_t        ic,
                        const uint8_t  *in,
                        uint8_t        *out,
                        size_t          len)
{
	uint8_t ctr[16];
	memcpy(ctr, nonce, 16);
	if (ic) ctr_add64(ctr, ic);
	serpent_ctr_xor_core(sk, ctr, in, out, len);
	sodium_memzero(ctr, sizeof ctr);
}

/*
 * serpent_ctr_xor_ic128 — encrypt/decrypt with a full 128-bit counter offset.
 *
 *   ic_lo  : low 64 bits of the block-count offset (bytes 0–7 of ctr, LE)
 *   ic_hi  : high 64 bits of the block-count offset (bytes 8–15 of ctr, LE)
 *
 * Used by worker pools: divide the input into N chunks, assign each worker
 * a start block = chunk_index * (chunk_size / 16), call xor_ic128 with that
 * offset, and process independently without any shared counter state.
 *
 * The full 128-bit range covers 2^128 × 16 bytes ≈ 5.4 × 10^39 bytes —
 * counter exhaustion is not a practical concern.
 *
 * Counter: ctr = nonce + (ic_lo | ic_hi<<64)  (128-bit LE addition).
 */
void serpent_ctr_xor_ic128(const uint32_t *sk,
                           const uint8_t   nonce[16],
                           uint64_t        ic_lo,
                           uint64_t        ic_hi,
                           const uint8_t  *in,
                           uint8_t        *out,
                           size_t          len)
{
	uint8_t ctr[16];
	memcpy(ctr, nonce, 16);
	if (ic_lo | ic_hi) ctr_add128(ctr, ic_lo, ic_hi);
	serpent_ctr_xor_core(sk, ctr, in, out, len);
	sodium_memzero(ctr, sizeof ctr);
}
